//TYPES Generales
export const INICIANDO_CONSULTA = 'INICIANDO_CONSULTA';
export const FINALIZANDO_CONSULTA = 'FINALIZANDO_CONSULTA';

//TYPES Login
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';


//TYPES Lottery
export const OBTENER_LOTERIAS = 'OBTENER_LOTERIAS';
export const OBTENER_TICKET = 'OBTENER_TICKET';
